Loaded 1000 rollouts
Loaded 1000 rollouts
> /home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/data/dataset.py(55)__init__()
-> sample = self.base[traj_idx]
102695
*** AttributeError: 'tuple' object has no attribute 'shape'
({}, tensor([[-0.5515,  0.8567],
        [-1.0317,  0.9741],
        [-1.4207,  0.4850],
        [-1.1862,  0.2112],
        [-0.9534,  0.0869],
        [-0.8200, -0.1376],
        [-0.5626,  0.0657],
        [-0.4969,  0.0921],
        [-0.4027,  0.2026],
        [-0.8078,  0.1358],
        [-0.8620,  0.2982],
        [-0.8005,  0.4355],
        [-0.6810,  0.0588],
        [-0.5395,  0.0617],
        [-0.2940,  0.1230],
        [-0.3873, -0.1274],
        [-0.3691,  0.0702],
        [-0.5418,  0.0465],
        [-0.8624,  0.1826],
        [-0.8983,  0.3039],
        [-0.7917,  0.5057]]), tensor([[ 0.0544, -2.2871, -1.4566, -0.9535, -0.0504, -3.2124, -0.1020,  0.5294],
        [ 0.0161, -2.2121, -1.4566, -0.9535, -0.0504, -3.2124, -0.5600,  0.8619],
        [-0.0606, -2.1207, -1.4566, -0.9535, -0.0504, -3.2124, -1.0417,  0.9783],
        [-0.1709, -2.0595, -1.4566, -0.9535, -0.0504, -3.2124, -1.4312,  0.4834],
        [-0.2761, -2.0296, -1.4566, -0.9535, -0.0504, -3.2124, -1.1919,  0.2100],
        [-0.3622, -2.0152, -1.4566, -0.9535, -0.0504, -3.2124, -0.9585,  0.0862],
        [-0.4352, -2.0192, -1.4566, -0.9535, -0.0504, -3.2124, -0.8254, -0.1398],
        [-0.4902, -2.0151, -1.4536, -0.9540,  0.0216, -3.2020, -0.5665,  0.0671],
        [-0.5355, -2.0039, -1.4505, -0.9546,  0.1087, -3.1864, -0.5019,  0.0924],
        [-0.5738, -1.9846, -1.4483, -0.9552,  0.1855, -3.1698, -0.4073,  0.2038],
        [-0.6339, -1.9670, -1.4462, -0.9558,  0.2955, -3.1412, -0.8167,  0.1357],
        [-0.7063, -1.9400, -1.4447, -0.9565,  0.4334, -3.0970, -0.8687,  0.3001],
        [-0.7762, -1.8996, -1.4450, -0.9566,  0.5727, -3.0422, -0.8063,  0.4378],
        [-0.8377, -1.8812, -1.4463, -0.9561,  0.6736, -2.9956, -0.6861,  0.0563],
        [-0.8881, -1.8724, -1.4471, -0.9558,  0.7572, -2.9521, -0.5441,  0.0618],
        [-0.9210, -1.8593, -1.4476, -0.9556,  0.8150, -2.9193, -0.2973,  0.1237],
        [-0.9538, -1.8616, -1.4479, -0.9554,  0.8576, -2.8935, -0.3930, -0.1298],
        [-0.9877, -1.8570, -1.4478, -0.9555,  0.9015, -2.8656, -0.3740,  0.0716],
        [-1.0314, -1.8488, -1.4474, -0.9559,  0.9615, -2.8250, -0.5484,  0.0463],
        [-1.0979, -1.8320, -1.4461, -0.9569,  1.0492, -2.7599, -0.8709,  0.1840],
        [-1.1736, -1.8034, -1.4439, -0.9591,  1.1505, -2.6750, -0.9050,  0.3056]]))
torch.Size([21, 2])
torch.Size([21, 8])
20
*** NameError: name 'seq_len' is not defined
> /home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/data/dataset.py(57)__init__()
-> state_seq = sample[2]
Traceback (most recent call last):
  File "/home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/train.py", line 144, in <module>
    main(sys.argv[1])
  File "/home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/train.py", line 63, in main
    train_ds, val_ds = load_pusht_dataset(cfg.data)
  File "/home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/data/dataset.py", line 40, in load_pusht_dataset
    train_ds = _RolloutDataset(train_base, data_cfg.num_pred)
  File "/home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/data/dataset.py", line 57, in __init__
    state_seq = sample[2]
  File "/home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/data/dataset.py", line 57, in __init__
    state_seq = sample[2]
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit